from __future__ import annotations

from typing import Protocol

from app.domain.models.plan import Plan


class PlanRepo(Protocol):
    # ---------- READ ----------
    async def list_active(self) -> list[Plan]: ...
    async def list_all(self) -> list[Plan]: ...
    async def get_by_id(self, plan_id: int) -> Plan | None: ...
    async def get_by_name(self, name: str) -> Plan | None: ...

    # ---------- WRITE ----------
    async def create(self, plan: Plan) -> Plan: ...
    async def update(self, plan_id: int, data: dict) -> Plan | None: ...
    async def delete(self, plan_id: int) -> bool: ...
