"""create client table

Revision ID: b60551d48ba7
Revises: 10ddfab633fb
Create Date: 2026-01-11 18:38:25.572515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b60551d48ba7'
down_revision: Union[str, Sequence[str], None] = '10ddfab633fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('fiscal_code', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('is_vat_payer', sa.Boolean(), nullable=False),
    sa.Column('contact_person', sa.String(length=120), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_company_id'), 'client', ['company_id'], unique=False)
    op.create_index('ix_client_company_name', 'client', ['company_id', 'name'], unique=False)
    op.create_index(op.f('ix_client_id'), 'client', ['id'], unique=False)
    op.create_index(op.f('ix_client_is_deleted'), 'client', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_is_deleted'), table_name='client')
    op.drop_index(op.f('ix_client_id'), table_name='client')
    op.drop_index('ix_client_company_name', table_name='client')
    op.drop_index(op.f('ix_client_company_id'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
